spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wangwangwang?useUnicode=true&charactorEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true